services:

 app:
   build: .
   container_name: app
   ports:
     - "80:5000"
   restart: always
   depends_on:
     - mongo
   environment:
     MONGO_URI: mongodb://mongo:27017/usersdb

 mongo:
   image: mongo
   container_name: mongo
   restart: always
   volumes:
     - mongo_data:/data/db

volumes:
 mongo_data: